# Used for development
version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - 8080:8080

  backend:
    build: ./backend
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/whatsbest?sslmode=disable
      - WAIT_HOSTS=postgres:5432
    depends_on:
      - postgres

  postgres:
    image: postgres
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=whatsbest
